server:
  port: '8082'

spring:
  profiles:
    active: profile2

---

spring:
  profiles: profile1
  datasource:
    url: jdbc:h2:mem:h2db
  h2:
    console:
      enable: 'true'
welcome:
  message: Welcome to new Application Profile 1

---

spring:
  profiles: profile2
  datasource:
    url: jdbc:h2:mem:h2db2
  h2:
    console:
      enable: 'true'
welcome:
  message: Welcome to new Application Profile 2

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "mappings,metrics,loggers,env,beans,info,conditions"

---

spring:
  profiles: profile3
  datasource:
    url: jdbc:h2:mem:h2db3
  h2:
    console:
      enable: 'true'
welcome:
  message: Welcome to new Application Profile 3